# Alertmanager Configuration for Microsoft 365 Management Tools
# Enterprise alerting with multiple notification channels

global:
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: '${ALERT_FROM_EMAIL}'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
    
    # High priority alerts
    - match:
        severity: high
      receiver: 'high-priority-alerts'
      repeat_interval: 15m
    
    # Warning alerts
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 1h
    
    # Microsoft 365 specific alerts
    - match:
        service: microsoft365
      receiver: 'microsoft365-alerts'
    
    # Database alerts
    - match:
        service: database
      receiver: 'database-alerts'
    
    # API alerts
    - match:
        service: api
      receiver: 'api-alerts'
    
    # Deployment strategy alerts
    - match_re:
        alertname: 'M365.*Deployment.*'
      receiver: 'deployment-alerts'
      repeat_interval: 10m
    
    # Blue-Green specific alerts
    - match:
        category: deployment
      match_re:
        alertname: '.*BlueGreen.*'
      receiver: 'blue-green-alerts'
    
    # Canary specific alerts
    - match:
        category: deployment
      match_re:
        alertname: '.*Canary.*'
      receiver: 'canary-alerts'

# Inhibition rules
inhibit_rules:
  # Inhibit warning if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
  
  # Inhibit high if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'high'
    equal: ['alertname', 'instance']

# Receivers configuration
receivers:
  # Default receiver
  - name: 'default'
    email_configs:
      - to: '${ALERT_TO_EMAILS}'
        subject: '[Microsoft 365 Tools] Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          Labels:
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          
          Firing: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ if .EndsAt }}Resolved: {{ .EndsAt.Format "2006-01-02 15:04:05" }}{{ end }}
          {{ end }}
        html: |
          <h2>Microsoft 365 Management Tools Alert</h2>
          {{ range .Alerts }}
          <h3>{{ .Annotations.summary }}</h3>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
          <p><strong>Service:</strong> {{ .Labels.service }}</p>
          <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
          <p><strong>Started:</strong> {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}</p>
          {{ if .EndsAt }}<p><strong>Resolved:</strong> {{ .EndsAt.Format "2006-01-02 15:04:05 UTC" }}</p>{{ end }}
          <hr>
          {{ end }}

  # Critical alerts receiver
  - name: 'critical-alerts'
    email_configs:
      - to: '${ALERT_TO_EMAILS}'
        subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }} - Microsoft 365 Tools'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          This is a critical alert requiring immediate attention!
          
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}
    
    # Microsoft Teams webhook (if configured)
    webhook_configs:
      - url: '${TEAMS_WEBHOOK_URL}'
        send_resolved: true
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          **Critical Alert - Immediate Action Required**
          
          {{ range .Alerts }}
          **Summary:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Instance:** {{ .Labels.instance }}
          **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}

  # High priority alerts
  - name: 'high-priority-alerts'
    email_configs:
      - to: '${ALERT_TO_EMAILS}'
        subject: '⚠️ HIGH: {{ .GroupLabels.alertname }} - Microsoft 365 Tools'
        body: |
          ⚠️ HIGH PRIORITY ALERT ⚠️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          This alert requires attention within 30 minutes.
          
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}

  # Warning alerts
  - name: 'warning-alerts'
    email_configs:
      - to: '${ALERT_TO_EMAILS}'
        subject: '⚠️ Warning: {{ .GroupLabels.alertname }} - Microsoft 365 Tools'
        body: |
          ⚠️ WARNING ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}

  # Microsoft 365 specific alerts
  - name: 'microsoft365-alerts'
    email_configs:
      - to: '${ALERT_TO_EMAILS}'
        subject: '🏢 Microsoft 365: {{ .GroupLabels.alertname }}'
        body: |
          🏢 MICROSOFT 365 ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          This alert is related to Microsoft 365 services and may affect user productivity.
          
          Service: {{ .Labels.service }}
          Component: {{ .Labels.component }}
          Tenant: {{ .Labels.tenant_id }}
          
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}

  # Database alerts
  - name: 'database-alerts'
    email_configs:
      - to: '${ALERT_TO_EMAILS}'
        subject: '🗄️ Database: {{ .GroupLabels.alertname }}'
        body: |
          🗄️ DATABASE ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          Database issues may affect application functionality.
          
          Database: {{ .Labels.database }}
          Instance: {{ .Labels.instance }}
          
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}

  # API alerts
  - name: 'api-alerts'
    email_configs:
      - to: '${ALERT_TO_EMAILS}'
        subject: '🔌 API: {{ .GroupLabels.alertname }}'
        body: |
          🔌 API ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          API issues may affect system integration and user experience.
          
          Endpoint: {{ .Labels.endpoint }}
          Method: {{ .Labels.method }}
          Status: {{ .Labels.status_code }}
          
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}

  # Deployment strategy alerts
  - name: 'deployment-alerts'
    email_configs:
      - to: '${ALERT_TO_EMAILS}'
        subject: '🚀 Deployment: {{ .GroupLabels.alertname }}'
        body: |
          🚀 DEPLOYMENT ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          Deployment strategy alert - requires immediate attention to ensure zero-downtime deployment.
          
          Deployment Type: {{ .Labels.deployment_type }}
          Version: {{ .Labels.version }}
          Service: {{ .Labels.service }}
          
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}

  # Blue-Green deployment alerts
  - name: 'blue-green-alerts'
    email_configs:
      - to: '${ALERT_TO_EMAILS}'
        subject: '🔵🟢 Blue-Green: {{ .GroupLabels.alertname }}'
        body: |
          🔵🟢 BLUE-GREEN DEPLOYMENT ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          Blue-Green deployment issue detected. Check traffic routing and service health.
          
          Deployment Version: {{ .Labels.deployment_version }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}

  # Canary deployment alerts
  - name: 'canary-alerts'
    email_configs:
      - to: '${ALERT_TO_EMAILS}'
        subject: '🐤 Canary: {{ .GroupLabels.alertname }}'
        body: |
          🐤 CANARY DEPLOYMENT ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          Canary deployment showing issues. Consider rollback or traffic adjustment.
          
          Canary Weight: {{ .Labels.canary_weight }}%
          Service: {{ .Labels.service }}
          Version: {{ .Labels.version }}
          
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}
    webhook_configs:
      - url: '${TEAMS_WEBHOOK_URL}'
        send_resolved: true
        title: '🐤 Canary Deployment Alert'
        text: |
          **Canary Deployment Issue Detected**
          
          {{ range .Alerts }}
          **Summary:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Canary Traffic:** {{ .Labels.canary_weight }}%
          **Service:** {{ .Labels.service }}
          **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}

# Templates for custom formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'