apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "m365-tools.fullname" . }}{{ if .Values.deployment.version }}-{{ .Values.deployment.version }}{{ end }}
  labels:
    {{- include "m365-tools.labels" . | nindent 4 }}
    {{- if .Values.deployment.version }}
    version: {{ .Values.deployment.version }}
    {{- end }}
  annotations:
    deployment.kubernetes.io/revision: "{{ .Release.Revision }}"
    {{- with .Values.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    {{- if eq .Values.deployment.type "canary" }}
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: {{ .Values.canary.maxSurge | default "25%" }}
    {{- else if eq .Values.deployment.type "blue-green" }}
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
    {{- else }}
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
    {{- end }}
  selector:
    matchLabels:
      {{- include "m365-tools.selectorLabels" . | nindent 6 }}
      {{- if .Values.deployment.version }}
      version: {{ .Values.deployment.version }}
      {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if eq .Values.deployment.type "canary" }}
        rollouts.argoproj.io/canary-weight: "{{ .Values.deployment.canaryWeight | default 10 }}"
        rollouts.argoproj.io/canary-step: "{{ .Values.deployment.canaryStep | default 0 }}"
        {{- end }}
        {{- if eq .Values.deployment.type "blue-green" }}
        rollouts.argoproj.io/blue-green: "true"
        rollouts.argoproj.io/active-service: {{ include "m365-tools.fullname" . }}-active
        rollouts.argoproj.io/preview-service: {{ include "m365-tools.fullname" . }}-preview
        {{- end }}
        {{- with .Values.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "m365-tools.selectorLabels" . | nindent 8 }}
        {{- if .Values.deployment.version }}
        version: {{ .Values.deployment.version }}
        {{- end }}
        {{- with .Values.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "m365-tools.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel }}
            - name: DEBUG
              value: {{ .Values.config.debug | quote }}
            - name: MICROSOFT_TENANT_ID
              value: {{ .Values.config.microsoft365.tenantId }}
            - name: MICROSOFT_CLIENT_ID
              value: {{ .Values.config.microsoft365.clientId }}
            - name: MICROSOFT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "m365-tools.fullname" . }}-secret
                  key: microsoft-client-secret
            - name: DATABASE_HOST
              value: {{ .Values.config.database.host }}
            - name: DATABASE_PORT
              value: {{ .Values.config.database.port | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.config.database.name }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "m365-tools.fullname" . }}-secret
                  key: database-password
            - name: REDIS_HOST
              value: {{ .Values.config.redis.host }}
            - name: REDIS_PORT
              value: {{ .Values.config.redis.port | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "m365-tools.fullname" . }}-secret
                  key: redis-password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "m365-tools.fullname" . }}-secret
                  key: secret-key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "m365-tools.fullname" . }}-secret
                  key: jwt-secret-key
            - name: PROMETHEUS_METRICS_ENABLED
              value: {{ .Values.monitoring.enabled | quote }}
            - name: HEALTH_CHECK_INTERVAL
              value: "30"
            - name: DEPLOYMENT_TYPE
              value: {{ .Values.deployment.type | quote }}
            - name: DEPLOYMENT_VERSION
              value: {{ .Values.deployment.version | default "stable" | quote }}
            {{- if eq .Values.deployment.type "canary" }}
            - name: CANARY_WEIGHT
              value: {{ .Values.deployment.canaryWeight | default 10 | quote }}
            - name: CANARY_ENABLED
              value: "true"
            {{- end }}
            {{- if eq .Values.deployment.type "blue-green" }}
            - name: BLUE_GREEN_ENABLED
              value: "true"
            - name: ACTIVE_VERSION
              value: {{ .Values.blueGreen.activeVersion | default "blue" | quote }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            {{- toYaml .Values.healthCheck.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.healthCheck.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: app-data
              mountPath: /app/data
            {{- if .Values.persistence.enabled }}
            - name: persistent-storage
              mountPath: /app/storage
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: app-data
          emptyDir: {}
        {{- if .Values.persistence.enabled }}
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "m365-tools.fullname" . }}-pvc
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "m365-tools.fullname" . }}{{ if .Values.deployment.version }}-{{ .Values.deployment.version }}{{ end }}
  labels:
    {{- include "m365-tools.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "m365-tools.fullname" . }}{{ if .Values.deployment.version }}-{{ .Values.deployment.version }}{{ end }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
---
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "m365-tools.fullname" . }}
  labels:
    {{- include "m365-tools.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "m365-tools.selectorLabels" . | nindent 6 }}
{{- end }}