{{- if eq .Values.deployment.type "canary" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "m365-tools.fullname" . }}-stable
  labels:
    {{- include "m365-tools.labels" . | nindent 4 }}
    service-type: "stable"
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /health
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "m365-tools.selectorLabels" . | nindent 4 }}
    # Stable version selector - managed by Argo Rollouts
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "m365-tools.fullname" . }}-canary
  labels:
    {{- include "m365-tools.labels" . | nindent 4 }}
    service-type: "canary"
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /health
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "m365-tools.selectorLabels" . | nindent 4 }}
    # Canary version selector - managed by Argo Rollouts
{{- end }}